# Generated by Django 3.2.12 on 2022-02-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0003_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
