# Generated by Django 3.2.12 on 2022-02-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0004_coursemodel_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
