# Generated by Django 3.2.12 on 2022-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0005_auto_20220223_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRetireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('id_course', models.IntegerField(unique=True)),
                ('scheduled_removal_date', models.DateTimeField()),
                ('language', models.CharField(max_length=2000)),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('course_category', models.CharField(max_length=2000)),
                ('course_subcategory', models.CharField(max_length=2000)),
                ('alternative_course_1', models.IntegerField()),
                ('title_alternative_course_1', models.IntegerField()),
                ('alternative_course_2', models.IntegerField()),
                ('title_alternative_course_2', models.IntegerField()),
            ],
        ),
    ]
