# Generated by Django 3.2.12 on 2022-03-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cursos', '0006_courseretiremodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseretiremodel',
            name='title_alternative_course_1',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='courseretiremodel',
            name='title_alternative_course_2',
            field=models.CharField(max_length=2000),
        ),
    ]
